name: /lustre/proyectos/p037/env_bdb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-nccl-cu12==2.28.9
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - propcache==0.4.1
      - psutil==7.1.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-triton-rocm==3.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.4.1+rocm6.1
      - torch-geometric==2.6.1
      - torchaudio==2.4.1+rocm6.1
      - torchvision==0.19.1+rocm6.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.1
      - xgboost==2.1.4
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /lustre/proyectos/p037/env_bdb
